# Generated by Django 5.2.17 on 2026-09-18 06:01

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0002_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="households.household"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=180)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="households.household"
                    ),
                ),
                (
                    "relation_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="households.relationtype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("object_type", models.CharField(max_length=50)),
                ("object_id", models.UUIDField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("before", models.JSONField(null=True)),
                ("after", models.JSONField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="households.household"
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "id"],
                "indexes": [
                    models.Index(fields=["household", "occurred_at"], name="audit_household_time"),
                    models.Index(fields=["household", "object_id"], name="audit_household_object"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IncomeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("category", models.CharField(max_length=100)),
                ("payer", models.CharField(blank=True, max_length=180)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "default_monthly_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        max_length=3,
                        validators=[django.core.validators.RegexValidator("^[A-Z]{3}$")],
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Miesięcznie"),
                            ("weekly", "Tygodniowo"),
                            ("quarterly", "Kwartalnie"),
                            ("yearly", "Rocznie"),
                            ("one_off", "Jednorazowo"),
                            ("irregular", "Nieregularnie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_regular", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="households.household"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="income_sources",
                        to="households.householdmember",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("deactivated_at__isnull", True), ("is_active", True)),
                            models.Q(("deactivated_at__isnull", False), ("is_active", False)),
                            _connector="OR",
                        ),
                        name="incomesource_archive_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("default_monthly_amount__gte", 0)),
                        name="income_nonnegative_amount",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="income_date_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "frequency__in",
                                [
                                    "monthly",
                                    "weekly",
                                    "quarterly",
                                    "yearly",
                                    "one_off",
                                    "irregular",
                                ],
                            )
                        ),
                        name="income_valid_frequency",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="relationtype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deactivated_at__isnull", True), ("is_active", True)),
                    models.Q(("deactivated_at__isnull", False), ("is_active", False)),
                    _connector="OR",
                ),
                name="relationtype_archive_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("household", "name"),
                name="unique_active_relation_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="householdmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("deactivated_at__isnull", True), ("is_active", True)),
                    models.Q(("deactivated_at__isnull", False), ("is_active", False)),
                    _connector="OR",
                ),
                name="householdmember_archive_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="householdmember",
            constraint=models.UniqueConstraint(
                fields=("household", "account"), name="unique_household_member_account"
            ),
        ),
    ]
