# Generated by Django 5.2.17 on 2026-10-07 10:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0004_family_income"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("calendar_year", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_years",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-calendar_year", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountingMonth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("month_number", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("inactive", "Nieaktywny"),
                            ("active", "Aktywny"),
                            ("closed", "Zamknięty"),
                        ],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accounting_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="months",
                        to="households.accountingyear",
                    ),
                ),
            ],
            options={
                "ordering": ["month_number", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="accountingyear",
            constraint=models.UniqueConstraint(
                fields=("household", "calendar_year"), name="acct_year_household_year_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountingyear",
            constraint=models.CheckConstraint(
                condition=models.Q(("calendar_year__gte", 1), ("calendar_year__lte", 9999)),
                name="acct_year_calendar_year_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountingmonth",
            constraint=models.UniqueConstraint(
                fields=("accounting_year", "month_number"), name="acct_month_year_number_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountingmonth",
            constraint=models.CheckConstraint(
                condition=models.Q(("month_number__gte", 1), ("month_number__lte", 12)),
                name="acct_month_number_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountingmonth",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["inactive", "active", "closed"])),
                name="acct_month_valid_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountingmonth",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activated_at__isnull", True),
                        ("closed_at__isnull", True),
                        ("state", "inactive"),
                    ),
                    models.Q(("activated_at__isnull", False), ("state", "active")),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("closed_at__isnull", False),
                        ("state", "closed"),
                    ),
                    _connector="OR",
                ),
                name="acct_month_state_timestamps_valid",
            ),
        ),
    ]
