# Generated by Django 5.2.17 on 2026-10-07 20:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("households", "0006_income_record_and_idempotency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("upload_batch_id", models.UUIDField(db_index=True)),
                ("original_name", models.CharField(max_length=255)),
                ("media_type", models.CharField(max_length=40)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("storage_key", models.CharField(max_length=300, unique=True)),
                ("content_sha256", models.CharField(max_length=64)),
                (
                    "availability_state",
                    models.CharField(
                        choices=[("available", "Dostępny"), ("removed", "Usunięty")],
                        default="available",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("storage_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_income_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="households.household"
                    ),
                ),
                (
                    "income_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="households.incomerecord",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="removed_income_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=[
                            "household",
                            "income_record",
                            "availability_state",
                            "created_at",
                            "id",
                        ],
                        name="income_att_owner_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("availability_state", "removed"), ("storage_deleted_at__isnull", True)
                        ),
                        fields=["storage_deleted_at"],
                        name="income_att_cleanup_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("size_bytes__gt", 0), ("size_bytes__lte", 10485760)),
                        name="income_att_size_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("content_sha256__regex", "^[0-9a-f]{64}$")),
                        name="income_att_sha256_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("availability_state", "available"),
                                ("removed_at__isnull", True),
                                ("removed_by__isnull", True),
                                ("storage_deleted_at__isnull", True),
                            ),
                            models.Q(
                                ("availability_state", "removed"),
                                ("removed_at__isnull", False),
                                ("removed_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="income_att_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("availability_state__in", ["available", "removed"])),
                        name="income_att_state_choice",
                    ),
                ],
            },
        ),
    ]
